---
title: "Bayesian Estimation"
output: html_notebook
---

```{r, message=F, warning=F}
library(dplyr)
library(ggplot2)
library(MASS)
```

```{r}
load = read.csv(paste0("C:/Users/Ong Jia Yi/Desktop/STUDY/Summer 2021/",
                      "Rotman MMA Summer 2021 Datathon/",
                      "NWHL.csv"),
                stringsAsFactors = FALSE)
```

```{r, message=F}
success = load %>%
  filter(Event == "Faceoff Win") %>%
  select(Player) %>%
  group_by(Player) %>%
  summarise(success=n())

failure = load %>%
  filter(Event == "Faceoff Win") %>%
  select(Player.2) %>%
  group_by(Player.2) %>%
  summarise(success=n())
```

```{r}
data = full_join(success, failure, by = c("Player" = "Player.2")) %>%
  rename(success = success.x, fail = success.y) %>%
  replace(is.na(.), 0) %>%
  mutate(N = success + fail, 
         rate = success/N)
```


## Method of Moments

```{r}
method_of_moments = function(m1, m2){
  # Returns the estimates for the alpha and beta parameters
  # of the Beta distribution using the Method of Moments.
  
  a = m1 * (m1 - m2) / (m2 - m1^2)
  b = (1 - m1) * (m1 - m2) / (m2 - m1^2)
  
  return(list("alpha" = a, "beta" = b))
}
```

Computing sample moments from sub-sample with outliers removed
```{r}
sample = data$rate[data$rate > 0.05 & data$rate < 0.9]
n = length(sample)
m1 = sum(sample)/n
m2 = sum(sample^2)/n
n; m1; m2
```

```{r}
a_hat = method_of_moments(m1, m2)$alpha
b_hat = method_of_moments(m1, m2)$beta
a_hat; b_hat
```


## Plot

```{r}
breaks = 20
xlim = c(0,1)
ylim= c(0,4)
lwd = 2
transparent = 1/3

histogram = hist(data$rate, 
                 breaks = breaks, plot = T, probability = T,
                 col=rgb(0,0,1,transparent), xlim = xlim, ylim = ylim, 
                 main = "Face-off Success Rates for Players",
                 xlab = "Success Rate")
grid()
xSeq = seq(0, 1, len=1000)
lines(xSeq, dbeta(xSeq, a_hat, b_hat), col = "BLUE", lwd = lwd)
```


## Updating success rate

```{r}
update = function(y, N, a, b){
  p_tilde = (a + y)/(a + b + N)
  
  return(p_tilde)
}
```

```{r}
a_hat / (a_hat + b_hat)
```

```{r}
data %>%
  rowwise() %>%
  mutate(p_tilde = update(success, N, a_hat, b_hat)) %>%
  arrange(desc(p_tilde))
```

